services:
  postgres:
    container_name: clean-postgres
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Passord01
      - POSTGRES_DB=mydb
    ports:
      - 5432:5432
    volumes:
      - clean-postgres:/var/lib/postgresql/data/

volumes:
  clean-postgres: